# Generated by Django 2.0.1 on 2018-01-19 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space_imager_profile', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Space_Image',
            new_name='Space_Photo_From_API_Model',
        ),
    ]
