# Generated by Django 2.0.1 on 2018-01-23 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space_imager_profile', '0003_auto_20180123_0031'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='SpacePhoto',
        ),
    ]
