# Generated by Django 2.0.1 on 2018-01-23 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_imager_profile', '0004_auto_20180123_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='spacephoto',
            name='url',
            field=models.CharField(max_length=180, null=True),
        ),
        migrations.AlterField(
            model_name='spacephoto',
            name='title',
            field=models.TextField(max_length=50),
        ),
    ]
