# Generated by Django 2.0.1 on 2018-01-23 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_imager_profile', '0005_auto_20180123_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='spacephoto',
            name='copyright',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='spacephoto',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='spacephoto',
            name='explanation',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='spacephoto',
            name='hdurl',
            field=models.CharField(max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='spacephoto',
            name='media_type',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='spacephoto',
            name='service_version',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
