# Generated by Django 2.0.1 on 2018-01-23 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space_imager_profile', '0006_auto_20180123_2327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spacephoto',
            name='copyright',
        ),
    ]
