# Generated by Django 2.0.1 on 2018-01-25 18:11

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('space_imager_profile', '0007_remove_spacephoto_copyright'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SpacePhoto',
            new_name='SpacePhotoFromNASA',
        ),
        migrations.AlterModelManagers(
            name='spacephotofromnasa',
            managers=[
                ('get_create_method_from_creator', django.db.models.manager.Manager()),
            ],
        ),
    ]
