# Generated by Django 2.0.1 on 2018-01-25 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space_imager_profile', '0008_auto_20180125_1811'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SpacePhotoFromNASA',
            new_name='Space_Photo_From_NASA',
        ),
    ]
